// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: protos/linkshorter.proto

package linkshorter_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginalLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *OriginalLink) Reset() {
	*x = OriginalLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_linkshorter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalLink) ProtoMessage() {}

func (x *OriginalLink) ProtoReflect() protoreflect.Message {
	mi := &file_protos_linkshorter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalLink.ProtoReflect.Descriptor instead.
func (*OriginalLink) Descriptor() ([]byte, []int) {
	return file_protos_linkshorter_proto_rawDescGZIP(), []int{0}
}

func (x *OriginalLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ShortLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *ShortLink) Reset() {
	*x = ShortLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_linkshorter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLink) ProtoMessage() {}

func (x *ShortLink) ProtoReflect() protoreflect.Message {
	mi := &file_protos_linkshorter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLink.ProtoReflect.Descriptor instead.
func (*ShortLink) Descriptor() ([]byte, []int) {
	return file_protos_linkshorter_proto_rawDescGZIP(), []int{1}
}

func (x *ShortLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_protos_linkshorter_proto protoreflect.FileDescriptor

var file_protos_linkshorter_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x69, 0x6e, 0x6b,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x0c, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x1f, 0x0a, 0x09, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x32, 0x80, 0x01, 0x0a,
	0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x04, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x16, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x38, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x42,
	0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x72,
	0x61, 0x66, 0x74, 0x62, 0x65, 0x63, 0x2f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x3b, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_linkshorter_proto_rawDescOnce sync.Once
	file_protos_linkshorter_proto_rawDescData = file_protos_linkshorter_proto_rawDesc
)

func file_protos_linkshorter_proto_rawDescGZIP() []byte {
	file_protos_linkshorter_proto_rawDescOnce.Do(func() {
		file_protos_linkshorter_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_linkshorter_proto_rawDescData)
	})
	return file_protos_linkshorter_proto_rawDescData
}

var file_protos_linkshorter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_linkshorter_proto_goTypes = []interface{}{
	(*OriginalLink)(nil), // 0: linkShorter.OriginalLink
	(*ShortLink)(nil),    // 1: linkShorter.ShortLink
}
var file_protos_linkshorter_proto_depIdxs = []int32{
	0, // 0: linkShorter.Shortener.Post:input_type -> linkShorter.OriginalLink
	1, // 1: linkShorter.Shortener.Get:input_type -> linkShorter.ShortLink
	1, // 2: linkShorter.Shortener.Post:output_type -> linkShorter.ShortLink
	0, // 3: linkShorter.Shortener.Get:output_type -> linkShorter.OriginalLink
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_linkshorter_proto_init() }
func file_protos_linkshorter_proto_init() {
	if File_protos_linkshorter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_linkshorter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_linkshorter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_linkshorter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_linkshorter_proto_goTypes,
		DependencyIndexes: file_protos_linkshorter_proto_depIdxs,
		MessageInfos:      file_protos_linkshorter_proto_msgTypes,
	}.Build()
	File_protos_linkshorter_proto = out.File
	file_protos_linkshorter_proto_rawDesc = nil
	file_protos_linkshorter_proto_goTypes = nil
	file_protos_linkshorter_proto_depIdxs = nil
}
